name: repro

on: push

jobs:
  repro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - uses: actions/checkout@v2
      - name: Run Tests
        run: go test -json -v "./..." | tee test.json | jq -jr '.Output | select (. != null )'
        shell: bash
      - name: Annotate Failures
        if: always()
        uses: ./golang-test-annotations
        with:
          test-results: test.json
