name: repro

on: push
#  push:
#    branches: 
#      - 'master'
#  pull_request:
#    branches:
#      - 'master'

jobs:
  repro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.5
      - uses: actions/checkout@v2
      - name: Run Tests
        run: go test -json -v "./..." | tee test.json | jq -jr '.Output | select (. != null )'
        shell: bash
      - name: Annotate Failures
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.0
        with:
          test-results: test.json
